resolver: lts-6.0
# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
extra-deps:
- th-lift-instances-0.1.7
- th-utilities-0.2.0.1
- store-0.2.1.0
- th-orphans-0.13.1
- http-client-0.5.0
- http-client-tls-0.3.0
- http-conduit-2.2.0
- path-0.5.8
